name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.1

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  toastification: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SfProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
    - family: SfProText
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
